### ISSUE TITLE
Validate blame phase logic / proofs

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/fusiondart#14]
Test the blame phase logic with a malicious or incompetent player.

**Comment by sneurlax** [comment]
We can test this with a player that fails to sign their own commitments.  You can:
 - not schedule a signature for submission
 - reverse the signature
 - flip or fudge a middle bit (recommended)

**Comment by sneurlax** [comment]
```
flutter: 2023-10-26T23:25:48.605195:: END OF RECV2
flutter: 2023-10-26T23:25:48.618158:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.623444:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.627823:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.632206:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.636592:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.641063:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.645673:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.649848:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.653978:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.657925:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.661861:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.665802:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.669730:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.673693:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.677784:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.681743:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.685708:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.689882:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.694984:: found an erroneous proof: Validation error: salt commitment mismatch
flutter: 2023-10-26T23:25:48.695020:: checked 19 proofs, 0 of them inputs
flutter: 2023-10-26T23:25:48.695436:: sending blames
flutter: 2023-10-26T23:25:48.695526:: ======= FusionStatus update ====================================
flutter: 2023-10-26T23:25:48.695543:: =~ Status: FusionStatus.running
flutter: 2023-10-26T23:25:48.695553:: =~   info: Awaiting restart
flutter: 2023-10-26T23:25:48.695562:: ================================================================
flutter: 2023-10-26T23:25:48.695580:: START OF RECV2
flutter: 2023-10-26T23:25:48.865180:: DEBUG recv_message2 1 - about to read the header
flutter: 2023-10-26T23:25:48.865237:: DEBUG recv_message2 4 - message received, length: 154
flutter: 2023-10-26T23:25:48.865319:: DEBUG recv_message2 5 - message content: [122, 151, 1, 10, 148, 1, 98, 97, 100, 32, 98, 108, 97, 109, 101, 32, 109, 101, 115, 115, 97, 103, 101, 58, 32, 86, 97, 108, 105, 100, 97, 116, 105, 111, 110, 32, 101, 114, 114, 111, 114, 58, 32, 98, 108, 97, 109, 101, 32, 105, 110, 100, 105, 99, 97, 116, 101, 100, 32, 105, 110, 116, 101, 114, 110, 97, 108, 32, 105, 110, 99, 111, 110, 115, 105, 115, 116, 101, 110, 99, 121, 44, 32, 110, 111, 110, 101, 32, 102, 111, 117, 110, 100, 33, 32, 40, 121, 111, 117, 32, 99, 108, 97, 105, 109, 101, 100, 58, 32, 39, 86, 97, 108, 105, 100, 97, 116, 105, 111, 110, 32, 101, 114, 114, 111, 114, 58, 32, 115, 97, 108, 116, 32, 99, 111, 109, 109, 105, 116, 109, 101, 110, 116, 32, 109, 105, 115, 109, 97, 116, 99, 104, 39, 41]
flutter: 2023-10-26T23:25:48.865367:: END OF RECV2
flutter: 2023-10-26T23:25:48.866301:: runRound failed: FusionError: Server error: "bad blame message: Validation error: blame indicated internal inconsistency, none found! (you claimed: 'Validation error: salt commitment mismatch')"
#0      Comms.recvPb (package:fusiondart/src/comms.dart:73:9)
<asynchronous suspension>
#1      Fusion.runRound (package:fusiondart/src/fusion.dart:1815:5)
<asynchronous suspension>
#2      Fusion.fuse (package:fusiondart/src/fusion.dart:386:22)
<asynchronous suspension>
#3      FusionWalletInterface.fuse (package:stackwallet/services/mixins/fusion_wallet_interface.dart:624:11)
<asynchronous suspension>

flutter: 2023-10-26T23:25:48.866411:: ======= FusionStatus update ====================================
flutter: 2023-10-26T23:25:48.866449:: =~ Status: FusionStatus.failed
flutter: 2023-10-26T23:25:48.866474:: =~   info: FusionError: Server error: "bad blame message: Validation error: blame indicated internal inconsistency, none found! (you claimed: 'Validation error: salt commitment mismatch')"
flutter: 2023-10-26T23:25:48.866504:: ================================================================
...
flutter: Log: [Error][2023-10-27 04:25:48.914Z]: FusionError: Server error: "bad blame message: Validation error: blame indicated internal inconsistency, none found! (you claimed: 'Validation error: salt commitment mismatch')"
flutter: #0      Comms.recvPb (package:fusiondart/src/comms.dart:73:9)
flutter: <asynchronous suspension>
flutter: #1      Fusion.runRound (package:fusiondart/src/fusion.dart:1815:5)
flutter: <asynchronous suspension>
flutter: #2      Fusion.fuse (package:fusiondart/src/fusion.dart:386:22)
flutter: <asynchronous suspension>
flutter: #3      FusionWalletInterface.fuse (package:stackwallet/services/mixins/fusion_wallet_interface.dart:624:11)
flutter: <asynchronous suspension>
flutter: 
```

**Comment by sneurlax** [comment]
This above exception seems to have been fixed by b0850e144ca340813cc656a7c5b9a4b954f7bd67
