### ISSUE TITLE
Handle Exception: recvMessage(): Should not reach this point

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/fusiondart#16]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: recvMessage(): Should not reach this point
#0      Connection.recvMessage (package:fusiondart/src/connection.dart:214:5)
<asynchronous suspension>
#1      Comms.recvPb (package:fusiondart/src/comms.dart:45:24)
<asynchronous suspension>
#2      Fusion.runRound (package:fusiondart/src/fusion.dart:1018:28)
<asynchronous suspension>
#3      Fusion.fuse (package:fusiondart/src/fusion.dart:360:20)
<asynchronous suspension>
#4      FusionWalletInterface.fuse (package:stackwallet/services/mixins/fusion_wallet_interface.dart:514:12)
<asynchronous suspension>
```

**Comment by sneurlax** [comment]
I haven't seen this since opening this issue.

**Comment by sneurlax** [comment]
I still haven't seen this happen recently.

**Comment by sneurlax** [comment]
Haven't seen this issue since initial report
